version: 0.2
phases:
  install:
    commands:
      - echo "Setting docker locally"
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - echo "Setting ECR permissions"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - LATEST=git describe --tags --abbrev=0 
      - docker build -t $IMAGE_REPO_URL:$LATEST .
  post_build:
    commands:
      - echo "Tests to be implemented in a future sprint!"
      - sleep 15
      - echo "Tests passed!"
      - echo "Pushing to ECR"
      - docker push $IMAGE_REPO_URL:$LATEST