version: 0.2
phases:
  pre-build:
    commands:
      - echo "Setting ECR permissions"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - LATEST=git describe --tags --abbrev=0 
      - docker build -t $IMAGE_REPO:$LATEST .
  test:
    commands:
      - echo "Tests to be implemented in a future sprint!"
      - echo "Tests passed!"
  push:
    commands:
      - docker push $IMAGE_REPO:$LATEST