# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\"<\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06phrase\x18\x03 \x01(\t\x12\n\n\x02pw\x18\x04 \x01(\t\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\",\n\x0fGetUserResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\".\n\x11\x43reateUserRequest\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\"/\n\x12\x43reateUserResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\",\n\x10LoginUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02pw\x18\x02 \x01(\t\".\n\x11LoginUserResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\".\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08greeting\x18\x02 \x01(\t\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"M\n\x14\x44\x65layedHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12$\n\x07request\x18\x02 \x03(\x0b\x32\x13.users.HelloRequest2\xc2\x03\n\x05Users\x12:\n\x07GetUser\x12\x15.users.GetUserRequest\x1a\x16.users.GetUserResponse\"\x00\x12\x43\n\nCreateUser\x12\x18.users.CreateUserRequest\x1a\x19.users.CreateUserResponse\"\x00\x12@\n\tLoginUser\x12\x17.users.LoginUserRequest\x1a\x18.users.LoginUserResponse\"\x00\x12\x35\n\x08SayHello\x12\x13.users.HelloRequest\x1a\x14.users.HelloResponse\x12<\n\rLotsOfReplies\x12\x13.users.HelloRequest\x1a\x14.users.HelloResponse0\x01\x12\x45\n\x0fLotsOfGreetings\x12\x13.users.HelloRequest\x1a\x1b.users.DelayedHelloResponse(\x01\x12:\n\tBidiHello\x12\x13.users.HelloRequest\x1a\x14.users.HelloResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=22
  _globals['_USER']._serialized_end=82
  _globals['_GETUSERREQUEST']._serialized_start=84
  _globals['_GETUSERREQUEST']._serialized_end=112
  _globals['_GETUSERRESPONSE']._serialized_start=114
  _globals['_GETUSERRESPONSE']._serialized_end=158
  _globals['_CREATEUSERREQUEST']._serialized_start=160
  _globals['_CREATEUSERREQUEST']._serialized_end=206
  _globals['_CREATEUSERRESPONSE']._serialized_start=208
  _globals['_CREATEUSERRESPONSE']._serialized_end=255
  _globals['_LOGINUSERREQUEST']._serialized_start=257
  _globals['_LOGINUSERREQUEST']._serialized_end=301
  _globals['_LOGINUSERRESPONSE']._serialized_start=303
  _globals['_LOGINUSERRESPONSE']._serialized_end=349
  _globals['_HELLOREQUEST']._serialized_start=351
  _globals['_HELLOREQUEST']._serialized_end=397
  _globals['_HELLORESPONSE']._serialized_start=399
  _globals['_HELLORESPONSE']._serialized_end=431
  _globals['_DELAYEDHELLORESPONSE']._serialized_start=433
  _globals['_DELAYEDHELLORESPONSE']._serialized_end=510
  _globals['_USERS']._serialized_start=513
  _globals['_USERS']._serialized_end=963
# @@protoc_insertion_point(module_scope)
